SELECT ID_PROYECTO, NOMBRE_PROYECTO, ESTADO, ID_LOCALIDAD FROM PROYECTO WHERE ESTADO = 'ACTIVO' ORDER BY NOMBRE_PROYECTO;

SELECT ID_USUARIO, CONCAT(NOMBRE_USUARIO, ' ', APELLIDO_USUARIO) AS NOMBRE, ID_AREA FROM USUARIO WHERE ID_USUARIO = 9;

SELECT E.ID_ESPECIALIDAD AS ID, E.TIPO_ESPECIALIDAD AS NOMBRE FROM ESPECIALIDAD E, AREA_ESPECIALIDAD A WHERE E.ID_ESPECIALIDAD = A.ID_ESPECIALIDAD AND A.ID_AREA = 22;

SELECT * FROM AREA_ESPECIALIDAD;